# Generated by Django 4.2 on 2024-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Electrico'), ('P', 'Planta')], max_length=30),
        ),
    ]
