# Generated by Django 4.2 on 2024-08-15 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_client_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('FUEGO', 'Fuego'), ('ELECTRICO', 'Electrico'), ('PSIQUICO', 'psiquico'), ('AGUA', 'Agua'), ('TIERRA', 'Tierra')], max_length=30),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.client')),
                ('productos', models.ManyToManyField(to='pokedex.book')),
            ],
        ),
    ]
